export type TeamData = {
    team_number: number;
    team_name: string;
    auto_coral_level_1: number;
    auto_coral_level_2: number;
    auto_coral_level_3: number;
    auto_coral_level_4: number;
    auto_algae_processor: number;
    auto_algae_net: number;
    teleop_coral_level_1: number;
    teleop_coral_level_2: number;
    teleop_coral_level_3: number;
    teleop_coral_level_4: number;
    teleop_algae_processor: number;
    teleop_algae_net: number;
    teleop_algae_thrown: number;
    park_percentage: number;
    shallow_percentage: number;
    deep_percentage: number;
    initiation_line: number;
    defense_rating: number;
};