import { z } from "zod";

const MatchScoreBreakdown2024AllianceSchema = z.object({
  adjustPoints: z.number(),
  autoAmpNoteCount: z.number(),
  autoAmpNotePoints: z.number(),
  autoLeavePoints: z.number(),
  autoLineRobot1: z.enum(["No", "Yes"]),
  autoLineRobot2: z.enum(["No", "Yes"]),
  autoLineRobot3: z.enum(["No", "Yes"]),
  autoPoints: z.number(),
  autoSpeakerNoteCount: z.number(),
  autoSpeakerNotePoints: z.number(),
  coopNotePlayed: z.boolean(),
  coopertitionBonusAchieved: z.boolean(),
  coopertitionCriteriaMet: z.boolean(),
  endGameHarmonyPoints: z.number(),
  endGameNoteInTrapPoints: z.number(),
  endGameOnStagePoints: z.number(),
  endGameParkPoints: z.number(),
  endGameRobot1: z.string(),
  endGameRobot2: z.string(),
  endgameRobot3: z.string(),
  endGameSpotLightBonusPoints: z.number(),
  endGameTotalStagePoints: z.number(),
  ensembleBonusAchieved: z.boolean(),
  ensembleBonusOnStageRobotsThreshold: z.number(),
  ensembleBonusStagePointsThreshold: z.number(),
  foulCount: z.number(),
  foulPoints: z.number(),
  g206Penalty: z.boolean(),
  g408Penalty: z.boolean(),
  g424Penalty: z.boolean(),
  melodyBonusAchieved: z.boolean(),
  melodyBonusThreshold: z.number(),
  melodyBonusThresholdCoop: z.number(),
  melodyBonusThresholdNonCoop: z.number(),
  micCenterStage: z.boolean(),
  micStageLeft: z.boolean(),
  micStageRight: z.boolean(),
  rp: z.number(),
  techFoulCount: z.number(),
  teleopAmpNoteCount: z.number(),
  teleopAmpNotePoints: z.number(),
  teleopPoints: z.number(),
  teleopSpeakerNoteAmplifiedCount: z.number(),
  teleopSpeakerNoteAmplifiedPoints: z.number(),
  teleopSpeakerNoteCount: z.number(),
  teleopSpeakerNotePoints: z.number(),
  totalPoints: z.number(),
  trapCenterStage: z.boolean(),
  trapStageLeft: z.boolean(),
  trapStageRight: z.boolean(),
});

const MatchScoreBreakdown2024Schema = z.object({
  blue: MatchScoreBreakdown2024AllianceSchema,
  red: MatchScoreBreakdown2024AllianceSchema,
});

export { MatchScoreBreakdown2024AllianceSchema, MatchScoreBreakdown2024Schema };
