create type public.alliance as enum('red', 'blue', 'none');

create table public.stand_forms (
    id                      bigint generated by default as identity,
    team_number             integer not null,
    match_number            smallint not null,
    scouter                 uuid not null,
    auto_amp_notes          smallint not null default 0,
    auto_speaker_notes      smallint not null default 0,
    teleop_amp_notes        smallint not null default 0,
    teleop_speaker_notes    smallint not null default 0,
    shuttle_notes           smallint not null default 0,
    trap_notes              smallint not null default 0,
    initiation_line         boolean not null default false,
    climb                   boolean not null default false,
    spotlight               boolean not null default false,
    park                    boolean not null default false,
    number_on_chain         smallint not null default 0,
    defense                 smallint not null default 3,
    penalties               smallint not null default 0,
    notes                   varchar(1024) not null,
    alliance                alliance not null,
    approved                boolean not null default false,
    created_at              timestamp with time zone not null default now(),
    updated_at              timestamp with time zone not null default now()
    ) tablespace pg_default;

alter table public.stand_forms enable row level security;

create policy "Allow stand form submit permission access" on public.stand_forms for all using ((SELECT authorize ('standform.submit')));
create policy "Allow public stand form read access" on public.stand_forms for select using (true);